/**:
  ros__parameters:
    wheel_radius: .03
    wheel_thickness: .0254
    wheel_offset_radius: .1608455
    bottom_base_height: .05715
    chassis_height: .155575
    paddle_origin_offset: .1067562